"""empty message

Revision ID: 55fc90290cc9
Revises: 8816edd6cb2b
Create Date: 2021-09-06 00:40:02.759711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fc90290cc9'
down_revision = '8816edd6cb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', '_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('_value', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
